# Generated by Django 4.2.5 on 2023-11-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerID', models.CharField(help_text='Player ID', max_length=20)),
                ('PlayerName', models.CharField(max_length=100)),
                ('JerseyNumber', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
